---
codecov:
  require_ci_to_pass: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
coverage:
  status:
    patch:
      default:
        target: auto
    project:
      default:
        threshold: 0.3%
