---
name: "CI"

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sonar:
    name: SonarCloud
    uses: ansible/ansible-content-actions/.github/workflows/sonarcloud.yaml@main
    with:
      python_version: "3.12"
      test_command: "pytest tests/unit -v --cov-report xml --cov=./ -o 'addopts='"
    secrets:
      SONAR_TOKEN: ${{ secrets.ANSIBLE_COLLECTIONS_ORG_SONAR_TOKEN_CICD_BOT }}

  codecov:
    name: "Code Coverage"
    runs-on: ubuntu-latest
    if: >-
      !github.event.pull_request ||
      contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          show-progress: false

      - name: Checkout PR Branch Code
        if: github.event_name == 'pull_request_target'
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr
          git checkout pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible-core pytest pytest-cov pytest-ansible-units pytest-forked pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Unit Tests with Coverage
        run: pytest tests/unit -v --cov-report xml --cov=./ -o 'addopts='

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ vars.CODECOV_TOKEN }}

  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
    if: github.event_name == 'pull_request_target'

  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main

  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main

  unit-galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main

  integration:
    uses: ansible/ansible-content-actions/.github/workflows/integration.yaml@main

  report-status:
    if: ${{ always() && github.event_name == 'schedule' }}
    needs:
      - changelog
      - ansible-lint
      - sanity
      - unit-galaxy
      - integration
    uses: ansible/ansible-content-actions/.github/workflows/upload_upstream_results.yaml@main
    with:
      job_context: ${{ toJSON(needs) }}
      component_name: ${{ github.event.repository.name }}
      UPLOAD_USER: ${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}
      UPLOAD_URL: ${{ vars.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}
    secrets:
      UPLOAD_PASSWORD: ${{ secrets.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}

  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - sanity
      - unit-galaxy
      - ansible-lint
      - integration
      - sonar
      - codecov
      - report-status
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.changelog.result }}',
          '${{ needs.integration.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.unit-galaxy.result }}',
          '${{ needs.ansible-lint.result }}',
          '${{ needs.sonar.result }}',
          '${{ needs.codecov.result }}',
          '${{ needs.report-status.result }}'
          ])"
